name: Bump Version

on:
  workflow_run:
    workflows: 
      - Build
    types:
      - completed

jobs:
  bump:

    runs-on: ubuntu-latest

    outputs:
      nodeVersion: ${{ steps.bump_version.outputs.version }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: bump version
      id: bump_version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "::set-output name=version::$(echo $(node -p "require('./package.json').version.trim()"))"
        yarn version --patch
        git push
